
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: testtest
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled: true
server:
  servlet:
    context-path: /jokul

storage:
  location: upload-dir
  source: C:/Movie/%s.mp4